#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Stop and disable service
        systemctl stop walpserver || true
        systemctl disable walpserver || true
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0 